version: "3.6"
services:
  jupyterlab:
    image: mrcedee/jupyterlab_pyspark:v2
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./hdfs:/opt/workspace
  spark-master:
    image: mrcedee/spark-master:v2
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./hdfs:/opt/workspace
  spark-worker-1:
    image: mrcedee/spark-worker:v2
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - ./hdfs:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: mrcedee/spark-worker:v2
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - ./hdfs:/opt/workspace
    depends_on:
      - spark-master
  neo4j:
    hostname: neo4j
    image: neo4j:4.4.17-community
    environment:
      - NEO4J_dbms_mode=SINGLE
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=******
      - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
      - NEO4JLABS_PLUGINS=["graph-data-science"]
    expose:
      - 7474
      - 7473
      - 7687
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./hdfs:/var/lib/neo4j/import
  mongo:
    image: mongo
    container_name: 'mongo1'
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    container_name: 'mongoadmin1'
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8091:8091"